from __future__ import annotations

from typing import Protocol

from vocation.domain.criteria import AssessmentCriterion


class CriteriaRepository(Protocol):
    def list(self, *, active_only: bool = False) -> list[AssessmentCriterion]: ...
    def get(self, criterion_id: str) -> AssessmentCriterion | None: ...
    def create(self, criterion: AssessmentCriterion) -> AssessmentCriterion: ...
    def update(self, criterion: AssessmentCriterion) -> AssessmentCriterion: ...
    def set_active(self, criterion_id: str, active: bool) -> AssessmentCriterion: ...
    def reorder(self, criterion_ids: list[str]) -> list[AssessmentCriterion]: ...
    def is_referenced(self, criterion_id: str) -> bool: ...


class PersonalTriageRepository(Protocol):
    def assessment_history(self, opportunity_id: str) -> list[dict]: ...
    def current_assessments(self, opportunity_id: str) -> list[dict]: ...
    def get_assessment(self, assessment_id: str) -> dict | None: ...
    def create_assessment(self, opportunity_id: str, criterion_id: str, value: object, reasoning: str | None) -> dict: ...
    def revise_assessment(self, opportunity_id: str, assessment_id: str, value: object, reasoning: str | None) -> dict: ...
    def status(self, opportunity_id: str) -> str: ...
    def decide(
        self,
        opportunity_id: str,
        resulting_status: str,
        decision_type: str,
        reason: str | None,
        reverses: str | None = None,
    ) -> dict: ...
    def decisions(self, opportunity_id: str) -> list[dict]: ...
    def active_exclusion(self, opportunity_id: str) -> dict | None: ...


class PromptRunRepository(Protocol):
    def save_initial(
        self,
        *,
        search_profile: str,
        constraints: list[str],
        as_of_date: str,
        criteria_snapshot: list[dict],
        prompt_text: str,
    ) -> str: ...
