from __future__ import annotations

from typing import Protocol

from vocation.domain.criteria import AssessmentCriterion
from vocation.domain.external_links import ExternalLink
from vocation.domain.research_bundle import DuplicateCase, PostingIdentity
from vocation.domain.update_import import ExistingSubject, PromptContextSnapshot, SubjectType


class CriteriaRepository(Protocol):
    def list(self, *, active_only: bool = False) -> list[AssessmentCriterion]: ...
    def get(self, criterion_id: str) -> AssessmentCriterion | None: ...
    def create(self, criterion: AssessmentCriterion) -> AssessmentCriterion: ...
    def update(self, criterion: AssessmentCriterion) -> AssessmentCriterion: ...
    def set_active(self, criterion_id: str, active: bool) -> AssessmentCriterion: ...
    def reorder(self, criterion_ids: list[str]) -> list[AssessmentCriterion]: ...
    def is_referenced(self, criterion_id: str) -> bool: ...


class PostingIdentityRepository(Protocol):
    def get_posting(self, posting_id: str) -> PostingIdentity | None: ...
    def find_by_stable_key(self, stable_key: str) -> PostingIdentity | None: ...
    def find_by_normalized_canonical_url(self, normalized_url: str) -> PostingIdentity | None: ...


class ExternalLinkRepository(Protocol):
    def links_for_opportunity(self, opportunity_id: str) -> list[ExternalLink] | None: ...
    def links_for_posting(self, opportunity_id: str, posting_id: str) -> list[ExternalLink] | None: ...


class DuplicateCaseRepository(Protocol):
    def get(self, case_id: str) -> DuplicateCase | None: ...
    def find_by_pair(self, subject_type: str, left_subject_id: str, right_subject_id: str) -> DuplicateCase | None: ...
    def create(self, case: DuplicateCase) -> DuplicateCase: ...
    def list(self, *, subject_type: str | None = None, subject_id: str | None = None) -> list[DuplicateCase]: ...


class PromptContextSnapshotRepository(Protocol):
    def get(self, prompt_context_ref: str) -> PromptContextSnapshot | None: ...


class UpdateSubjectRepository(Protocol):
    def get(self, subject_type: SubjectType, subject_id: str) -> ExistingSubject | None: ...


class PersonalTriageRepository(Protocol):
    def assessment_history(self, opportunity_id: str) -> list[dict]: ...
    def current_assessments(self, opportunity_id: str) -> list[dict]: ...
    def get_assessment(self, assessment_id: str) -> dict | None: ...
    def create_assessment(self, opportunity_id: str, criterion_id: str, value: object, reasoning: str | None) -> dict: ...
    def revise_assessment(self, opportunity_id: str, assessment_id: str, value: object, reasoning: str | None) -> dict: ...
    def status(self, opportunity_id: str) -> str: ...
    def decide(
        self,
        opportunity_id: str,
        resulting_status: str,
        decision_type: str,
        reason: str | None,
        reverses: str | None = None,
    ) -> dict: ...
    def decisions(self, opportunity_id: str) -> list[dict]: ...
    def active_exclusion(self, opportunity_id: str) -> dict | None: ...


class PromptRunRepository(Protocol):
    def save_initial(
        self,
        *,
        search_profile: str,
        constraints: list[str],
        as_of_date: str,
        criteria_snapshot: list[dict],
        prompt_text: str,
    ) -> str: ...

    def save_update(
        self,
        *,
        prompt_type: str,
        as_of_date: str,
        research_scope: dict,
        prompt_context_ref: str,
        subject_mappings: list[dict],
        criteria_snapshot: list[dict],
        prompt_text: str,
    ) -> tuple[str, str]: ...

    def save_availability(
        self,
        *,
        as_of_date: str,
        research_scope: dict,
        prompt_context_ref: str,
        subject_mappings: list[dict],
        prompt_text: str,
    ) -> tuple[str, str]: ...
