/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Criteria */
        get: operations["list_criteria_api_criteria_get"];
        put?: never;
        /** Create Criterion */
        post: operations["create_criterion_api_criteria_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Criteria */
        post: operations["reorder_criteria_api_criteria_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/{criterion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Criterion */
        put: operations["edit_criterion_api_criteria__criterion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/{criterion_id}/activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Criterion */
        post: operations["activate_criterion_api_criteria__criterion_id__activation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import File */
        post: operations["import_file_api_imports_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Text */
        post: operations["import_text_api_imports_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Report */
        get: operations["get_import_report_api_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunity Detail */
        get: operations["opportunity_detail_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/initial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Initial Prompt */
        post: operations["generate_initial_prompt_api_prompts_initial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivationPayload */
        ActivationPayload: {
            /** Active */
            active: boolean;
        };
        /** AssessmentResponse */
        AssessmentResponse: {
            /** Criterion Id */
            criterion_id: string;
            /** Criterion Name */
            criterion_name: string;
            /** Id */
            id: string;
            /** Origin */
            origin: string;
            /** Reasoning */
            reasoning: string | null;
            /** Value */
            value: unknown;
        };
        /** Body_import_file_api_imports_file_post */
        Body_import_file_api_imports_file_post: {
            /** File */
            file: string;
        };
        /** CompanyResponse */
        CompanyResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CriterionPayload */
        CriterionPayload: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Allowed Values */
            allowed_values?: string[];
            /**
             * Applicable Subject Type
             * @enum {string}
             */
            applicable_subject_type: "company" | "opportunity" | "posting";
            /** Criterion Id */
            criterion_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Display Order
             * @default 10
             */
            display_order: number;
            /** Numeric Max */
            numeric_max?: number | null;
            /** Numeric Min */
            numeric_min?: number | null;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "numeric" | "boolean" | "categorical" | "text";
        };
        /** CriterionResponse */
        CriterionResponse: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Allowed Values */
            allowed_values?: string[];
            /**
             * Applicable Subject Type
             * @enum {string}
             */
            applicable_subject_type: "company" | "opportunity" | "posting";
            /** Criterion Id */
            criterion_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Display Order
             * @default 10
             */
            display_order: number;
            /** Numeric Max */
            numeric_max?: number | null;
            /** Numeric Min */
            numeric_min?: number | null;
            /** Revision */
            revision: number;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "numeric" | "boolean" | "categorical" | "text";
        };
        /** GeneratedPromptResponse */
        GeneratedPromptResponse: {
            /** Bundle Version */
            bundle_version: string;
            /** Criteria Count */
            criteria_count: number;
            /** Prompt Run Id */
            prompt_run_id: string;
            /** Prompt Text */
            prompt_text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportIssueResponse */
        ImportIssueResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Severity */
            severity: string;
        };
        /** ImportProvenanceResponse */
        ImportProvenanceResponse: {
            /** Applied At */
            applied_at: string;
            /** Bundle Id */
            bundle_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Import Id */
            import_id: string;
        };
        /** ImportReportResponse */
        ImportReportResponse: {
            /** Bundle Id */
            bundle_id: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Duplicate Of Import Id */
            duplicate_of_import_id?: string | null;
            /** Fingerprint */
            fingerprint: string | null;
            /** Import Id */
            import_id: string;
            /** Issues */
            issues: components["schemas"]["ImportIssueResponse"][];
            /** Status */
            status: string;
            /** Warnings */
            warnings: string[];
        };
        /** ImportTextPayload */
        ImportTextPayload: {
            /** Content */
            content: string;
        };
        /** InitialPromptPayload */
        InitialPromptPayload: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Constraints */
            constraints?: string[];
            /** Search Profile */
            search_profile: string;
        };
        /** LocationResponse */
        LocationResponse: {
            /** Evidence Summary */
            evidence_summary: string | null;
            /** Label */
            label: string;
            /** Precision */
            precision: string;
        };
        /** ObservationResponse */
        ObservationResponse: {
            /** Confidence */
            confidence: number | null;
            /** Evidence Summary */
            evidence_summary: string | null;
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Subject Type */
            subject_type: string;
            /** Type */
            type: string;
            /** Value */
            value: unknown;
        };
        /** OpportunityDetailResponse */
        OpportunityDetailResponse: {
            /** Assessments */
            assessments: components["schemas"]["AssessmentResponse"][];
            company: components["schemas"]["CompanyResponse"];
            /** Id */
            id: string;
            import_provenance: components["schemas"]["ImportProvenanceResponse"];
            /** Locations */
            locations: components["schemas"]["LocationResponse"][];
            /** Observations */
            observations: components["schemas"]["ObservationResponse"][];
            /** Postings */
            postings: components["schemas"]["PostingResponse"][];
            /** Sources */
            sources: components["schemas"]["SourceResponse"][];
            /** Title */
            title: string;
        };
        /** OpportunityListItemResponse */
        OpportunityListItemResponse: {
            /** Assessment Count */
            assessment_count: number;
            /** Company Name */
            company_name: string;
            /** Id */
            id: string;
            /** Import Id */
            import_id: string;
            /** Imported At */
            imported_at: string;
            /** Locations */
            locations: string[];
            /** Posting Count */
            posting_count: number;
            /** Title */
            title: string;
        };
        /** PostingResponse */
        PostingResponse: {
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Published At */
            published_at: string | null;
            source: components["schemas"]["SourceResponse"];
            source_reference: components["schemas"]["SourceReferenceResponse"];
            /** Title */
            title: string;
        };
        /** ReorderPayload */
        ReorderPayload: {
            /** Criterion Ids */
            criterion_ids: string[];
        };
        /** SourceReferenceResponse */
        SourceReferenceResponse: {
            /** Display Label */
            display_label: string | null;
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Url */
            url: string;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Base Url */
            base_url?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_criteria_api_criteria_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"][];
                };
            };
        };
    };
    create_criterion_api_criteria_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_criteria_api_criteria_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_criterion_api_criteria__criterion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_criterion_api_criteria__criterion_id__activation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    import_file_api_imports_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_api_imports_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_text_api_imports_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTextPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_report_api_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityListItemResponse"][];
                };
            };
        };
    };
    opportunity_detail_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_initial_prompt_api_prompts_initial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialPromptPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
