/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import File */
        post: operations["import_file_api_availability_imports_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/availability/imports/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Text */
        post: operations["import_text_api_availability_imports_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/availability/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Report */
        get: operations["get_import_report_api_availability_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Criteria */
        get: operations["list_criteria_api_criteria_get"];
        put?: never;
        /** Create Criterion */
        post: operations["create_criterion_api_criteria_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Criteria */
        post: operations["reorder_criteria_api_criteria_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/{criterion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Criterion */
        put: operations["edit_criterion_api_criteria__criterion_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria/{criterion_id}/activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Criterion */
        post: operations["activate_criterion_api_criteria__criterion_id__activation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group */
        get: operations["get_group_api_groups__group_id__get"];
        /** Edit Group */
        put: operations["edit_group_api_groups__group_id__put"];
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Membership */
        post: operations["add_membership_api_groups__group_id__memberships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/memberships/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Membership */
        delete: operations["remove_membership_api_groups__group_id__memberships__opportunity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Group */
        put: operations["reorder_group_api_groups__group_id__order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import File */
        post: operations["import_file_api_imports_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Text */
        post: operations["import_text_api_imports_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Report */
        get: operations["get_import_report_api_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Map Locations */
        get: operations["list_map_locations_api_map_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/locations/{work_location_id}/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Geocode Location */
        post: operations["geocode_location_api_map_locations__work_location_id__geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/locations/{work_location_id}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Resolution */
        put: operations["set_resolution_api_map_locations__work_location_id__resolution_put"];
        post?: never;
        /** Delete Resolution */
        delete: operations["delete_resolution_api_map_locations__work_location_id__resolution_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Map Projection */
        post: operations["map_projection_api_map_projection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunity Detail */
        get: operations["opportunity_detail_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/assessments/personal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Assessments */
        get: operations["personal_assessments_api_opportunities__opportunity_id__assessments_personal_get"];
        put?: never;
        /** Create Personal Assessment */
        post: operations["create_personal_assessment_api_opportunities__opportunity_id__assessments_personal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/assessments/personal/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Assessment History */
        get: operations["personal_assessment_history_api_opportunities__opportunity_id__assessments_personal_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/assessments/personal/{assessment_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Personal Assessment */
        post: operations["revise_personal_assessment_api_opportunities__opportunity_id__assessments_personal__assessment_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision History */
        get: operations["decision_history_api_opportunities__opportunity_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exclude */
        post: operations["exclude_api_opportunities__opportunity_id__exclude_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_opportunities__opportunity_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_api_opportunities__opportunity_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/availability-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Availability Prompt */
        post: operations["generate_availability_prompt_api_prompts_availability_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/initial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Initial Prompt */
        post: operations["generate_initial_prompt_api_prompts_initial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Update Prompt */
        post: operations["generate_update_prompt_api_prompts_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/update-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Update Prompt Options */
        get: operations["update_prompt_options_api_prompts_update_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivationPayload */
        ActivationPayload: {
            /** Active */
            active: boolean;
        };
        /** AssessmentResponse */
        AssessmentResponse: {
            /** Criterion Id */
            criterion_id: string;
            /** Criterion Name */
            criterion_name: string;
            /** Id */
            id: string;
            /** Origin */
            origin: string;
            /** Reasoning */
            reasoning: string | null;
            /** Value */
            value: unknown;
        };
        /** AvailabilityHistoryResponse */
        AvailabilityHistoryResponse: {
            /** Evidence Summary */
            evidence_summary: string;
            /** Id */
            id: string;
            /** Import Id */
            import_id: string;
            /** Observed At */
            observed_at: string;
            /** Recorded At */
            recorded_at: string;
            /** Result */
            result: string;
        };
        /** AvailabilityImportReportResponse */
        AvailabilityImportReportResponse: {
            /** Bundle Id */
            bundle_id: string | null;
            /** Bundle Version */
            bundle_version?: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Duplicate Of Import Id */
            duplicate_of_import_id?: string | null;
            /** Fingerprint */
            fingerprint: string | null;
            /** Import Id */
            import_id: string;
            /**
             * Import Kind
             * @constant
             */
            import_kind: "availability_check";
            /** Issues */
            issues: components["schemas"]["ImportIssueResponse"][];
            /** Prompt Context Ref */
            prompt_context_ref?: string | null;
            /** Status */
            status: string;
            /** Warnings */
            warnings: string[];
        };
        /** AvailabilityImportTextPayload */
        AvailabilityImportTextPayload: {
            /** Content */
            content: string;
        };
        /** AvailabilityPromptPayload */
        AvailabilityPromptPayload: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Posting Ids */
            posting_ids: string[];
        };
        /** Body_import_file_api_availability_imports_file_post */
        Body_import_file_api_availability_imports_file_post: {
            /** File */
            file: string;
        };
        /** Body_import_file_api_imports_file_post */
        Body_import_file_api_imports_file_post: {
            /** File */
            file: string;
        };
        /** CompanyOptionResponse */
        CompanyOptionResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CompanyResponse */
        CompanyResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CriterionPayload */
        CriterionPayload: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Allowed Values */
            allowed_values?: string[];
            /**
             * Applicable Subject Type
             * @enum {string}
             */
            applicable_subject_type: "company" | "opportunity" | "posting";
            /** Criterion Id */
            criterion_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Display Order
             * @default 10
             */
            display_order: number;
            /** Numeric Max */
            numeric_max?: number | null;
            /** Numeric Min */
            numeric_min?: number | null;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "numeric" | "boolean" | "categorical" | "text";
        };
        /** CriterionResponse */
        CriterionResponse: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Allowed Values */
            allowed_values?: string[];
            /**
             * Applicable Subject Type
             * @enum {string}
             */
            applicable_subject_type: "company" | "opportunity" | "posting";
            /** Criterion Id */
            criterion_id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Display Order
             * @default 10
             */
            display_order: number;
            /** Numeric Max */
            numeric_max?: number | null;
            /** Numeric Min */
            numeric_min?: number | null;
            /** Revision */
            revision: number;
            /**
             * Value Type
             * @enum {string}
             */
            value_type: "numeric" | "boolean" | "categorical" | "text";
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Created At */
            created_at: string;
            /** Decision Type */
            decision_type: string;
            /** Id */
            id: string;
            /** Opportunity Id */
            opportunity_id: string;
            /**
             * Previous Status
             * @enum {string}
             */
            previous_status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
            /** Reason */
            reason: string | null;
            /**
             * Resulting Status
             * @enum {string}
             */
            resulting_status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
            /** Reverses Decision Id */
            reverses_decision_id: string | null;
        };
        /** ExclusionPayload */
        ExclusionPayload: {
            /** Reason */
            reason: string;
        };
        /** FullResearchScope */
        FullResearchScope: {
            /** As Of Date */
            as_of_date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "full_update";
        };
        /** GapCriterionScopeRequest */
        GapCriterionScopeRequest: {
            /** Correlation Ref */
            correlation_ref: string;
            /** Criterion Id */
            criterion_id: string;
            /** Observation Type */
            observation_type?: null;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "company" | "opportunity" | "posting";
        };
        /** GapObservationScopeRequest */
        GapObservationScopeRequest: {
            /** Correlation Ref */
            correlation_ref: string;
            /** Criterion Id */
            criterion_id?: null;
            /**
             * Observation Type
             * @enum {string}
             */
            observation_type: "technology_requirement" | "task" | "seniority" | "experience_requirement" | "work_model" | "salary";
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "company" | "opportunity" | "posting";
        };
        /** GapRequestPayload */
        GapRequestPayload: {
            /** Criterion Id */
            criterion_id?: string | null;
            /** Observation Type */
            observation_type?: ("technology_requirement" | "task" | "seniority" | "experience_requirement" | "work_model" | "salary") | null;
            /** Subject Id */
            subject_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "company" | "opportunity" | "posting";
        };
        /** GapResearchScope */
        GapResearchScope: {
            /** As Of Date */
            as_of_date: string;
            /** Requests */
            requests: (components["schemas"]["GapObservationScopeRequest"] | components["schemas"]["GapCriterionScopeRequest"])[];
            /** Selected Correlation Refs */
            selected_correlation_refs: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gap_filling";
        };
        /** GeneratedAvailabilityPromptResponse */
        GeneratedAvailabilityPromptResponse: {
            /**
             * Bundle Kind
             * @constant
             */
            bundle_kind: "availability_check";
            /**
             * Bundle Version
             * @constant
             */
            bundle_version: "1.0";
            /** Prompt Context Ref */
            prompt_context_ref: string;
            /** Prompt Run Id */
            prompt_run_id: string;
            /** Prompt Text */
            prompt_text: string;
            /**
             * Prompt Type
             * @constant
             */
            prompt_type: "availability_check";
            /**
             * Prompt Version
             * @constant
             */
            prompt_version: "1.0";
            /** Research Scope */
            research_scope: {
                [key: string]: unknown;
            };
        };
        /** GeneratedPromptResponse */
        GeneratedPromptResponse: {
            /**
             * Bundle Version
             * @enum {string}
             */
            bundle_version: "1.0" | "2.0";
            /** Criteria Count */
            criteria_count: number;
            /** Prompt Run Id */
            prompt_run_id: string;
            /** Prompt Text */
            prompt_text: string;
        };
        /** GeneratedUpdatePromptResponse */
        GeneratedUpdatePromptResponse: {
            /**
             * Bundle Version
             * @constant
             */
            bundle_version: "2.0";
            /** Criteria Count */
            criteria_count: number;
            /** Prompt Context Ref */
            prompt_context_ref: string;
            /** Prompt Run Id */
            prompt_run_id: string;
            /** Prompt Text */
            prompt_text: string;
            /**
             * Prompt Type
             * @enum {string}
             */
            prompt_type: "full_update" | "company_update" | "opportunity_update" | "gap_filling";
            /** Prompt Version */
            prompt_version: string;
            /** Research Scope */
            research_scope: components["schemas"]["FullResearchScope"] | components["schemas"]["SelectedResearchScope"] | components["schemas"]["GapResearchScope"];
        };
        /** GeocodeResolutionPayload */
        GeocodeResolutionPayload: {
            /** Query */
            query: string;
        };
        /** GroupMembershipResponse */
        GroupMembershipResponse: {
            /** Company Name */
            company_name: string;
            /** Opportunity Id */
            opportunity_id: string;
            /** Opportunity Title */
            opportunity_title: string;
            /** Position */
            position: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportIssueResponse */
        ImportIssueResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Severity */
            severity: string;
        };
        /** ImportProvenanceResponse */
        ImportProvenanceResponse: {
            /** Applied At */
            applied_at: string;
            /** Bundle Id */
            bundle_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Import Id */
            import_id: string;
        };
        /** ImportReportResponse */
        ImportReportResponse: {
            /** Bundle Id */
            bundle_id: string | null;
            /** Bundle Version */
            bundle_version?: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Duplicate Of Import Id */
            duplicate_of_import_id?: string | null;
            /** Fingerprint */
            fingerprint: string | null;
            /** Import Id */
            import_id: string;
            /** Issues */
            issues: components["schemas"]["ImportIssueResponse"][];
            /** Prompt Context Ref */
            prompt_context_ref?: string | null;
            /** Status */
            status: string;
            /** Warnings */
            warnings: string[];
        };
        /** ImportTextPayload */
        ImportTextPayload: {
            /** Content */
            content: string;
        };
        /** InitialPromptPayload */
        InitialPromptPayload: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Constraints */
            constraints?: string[];
            /** Search Profile */
            search_profile: string;
        };
        /** LocationResponse */
        LocationResponse: {
            /** Evidence Summary */
            evidence_summary: string | null;
            /** Label */
            label: string;
            /** Precision */
            precision: string;
        };
        /** MapGroupMembershipResponse */
        MapGroupMembershipResponse: {
            /** Group Id */
            group_id: string;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "general" | "application_wave";
            /** Name */
            name: string;
        };
        /** MapLocationResponse */
        MapLocationResponse: {
            /** City */
            city: string | null;
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /** Country Code */
            country_code: string | null;
            /** Label */
            label: string;
            /** Opportunity Id */
            opportunity_id: string;
            /** Precision */
            precision: string;
            /** Region */
            region: string | null;
            resolution: components["schemas"]["MapResolutionResponse"] | null;
            /** Title */
            title: string;
            /** Work Location Id */
            work_location_id: string;
        };
        /** MapProjectionFeatureResponse */
        MapProjectionFeatureResponse: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "unavailable" | "uncertain" | "unknown";
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /** Feature Id */
            feature_id: string;
            /** Groups */
            groups: components["schemas"]["MapGroupMembershipResponse"][];
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string;
            /** Longitude */
            longitude: number;
            /** Opportunity Id */
            opportunity_id: string;
            /** Precision */
            precision: string;
            /** Title */
            title: string;
            /**
             * Tracking Status
             * @enum {string}
             */
            tracking_status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
            /** Work Location Id */
            work_location_id: string;
        };
        /** MapProjectionPayload */
        MapProjectionPayload: {
            /** Opportunity Ids */
            opportunity_ids?: string[];
        };
        /** MapResolutionPayload */
        MapResolutionPayload: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Resolved Query */
            resolved_query: string;
        };
        /** MapResolutionResponse */
        MapResolutionResponse: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Provider Key */
            provider_key: string | null;
            /**
             * Resolution Source
             * @enum {string}
             */
            resolution_source: "manual" | "geocoder";
            /** Resolved At */
            resolved_at: string;
            /** Resolved Query */
            resolved_query: string;
        };
        /** ObservationResponse */
        ObservationResponse: {
            /** Confidence */
            confidence: number | null;
            /** Evidence Summary */
            evidence_summary: string | null;
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Subject Type */
            subject_type: string;
            /** Type */
            type: string;
            /** Value */
            value: unknown;
        };
        /** OpportunityDetailResponse */
        OpportunityDetailResponse: {
            /** Assessments */
            assessments: components["schemas"]["AssessmentResponse"][];
            /** Availability */
            availability?: ("available" | "unavailable" | "uncertain" | "unknown") | null;
            /** Availability Age Days */
            availability_age_days?: number | null;
            /** Availability Last Checked At */
            availability_last_checked_at?: string | null;
            company: components["schemas"]["CompanyResponse"];
            /** Decision History */
            decision_history: components["schemas"]["DecisionResponse"][];
            /** External Assessments */
            external_assessments: components["schemas"]["AssessmentResponse"][];
            /** Groups */
            groups?: components["schemas"]["OpportunityGroupSummaryResponse"][];
            /** Id */
            id: string;
            import_provenance: components["schemas"]["ImportProvenanceResponse"];
            /** Locations */
            locations: components["schemas"]["LocationResponse"][];
            /** Observations */
            observations: components["schemas"]["ObservationResponse"][];
            /** Personal Assessment History */
            personal_assessment_history: components["schemas"]["PersonalAssessmentResponse"][];
            /** Personal Assessments */
            personal_assessments: components["schemas"]["PersonalAssessmentResponse"][];
            /** Postings */
            postings: components["schemas"]["PostingResponse"][];
            /** Sources */
            sources: components["schemas"]["SourceResponse"][];
            /** Title */
            title: string;
            /**
             * Tracking Status
             * @enum {string}
             */
            tracking_status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
        };
        /** OpportunityGroupMembershipPayload */
        OpportunityGroupMembershipPayload: {
            /** Opportunity Id */
            opportunity_id: string;
        };
        /** OpportunityGroupPayload */
        OpportunityGroupPayload: {
            /** Description */
            description?: string | null;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "general" | "application_wave";
            /** Name */
            name: string;
        };
        /** OpportunityGroupReorderPayload */
        OpportunityGroupReorderPayload: {
            /** Opportunity Ids */
            opportunity_ids: string[];
        };
        /** OpportunityGroupResponse */
        OpportunityGroupResponse: {
            /** Description */
            description: string | null;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "general" | "application_wave";
            /** Id */
            id: string;
            /** Memberships */
            memberships: components["schemas"]["GroupMembershipResponse"][];
            /** Name */
            name: string;
        };
        /** OpportunityGroupSummaryResponse */
        OpportunityGroupSummaryResponse: {
            /** Group Id */
            group_id: string;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "general" | "application_wave";
            /** Name */
            name: string;
        };
        /** OpportunityListItemResponse */
        OpportunityListItemResponse: {
            /** Assessment Count */
            assessment_count: number;
            /** Availability */
            availability?: ("available" | "unavailable" | "uncertain" | "unknown") | null;
            /** Availability Age Days */
            availability_age_days?: number | null;
            /** Availability Last Checked At */
            availability_last_checked_at?: string | null;
            /** Company Name */
            company_name: string;
            /** Groups */
            groups?: components["schemas"]["OpportunityGroupSummaryResponse"][];
            /** Id */
            id: string;
            /** Import Id */
            import_id: string;
            /** Imported At */
            imported_at: string;
            /** Locations */
            locations: string[];
            /** Posting Count */
            posting_count: number;
            /** Title */
            title: string;
            /**
             * Tracking Status
             * @enum {string}
             */
            tracking_status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
        };
        /** OpportunityOptionResponse */
        OpportunityOptionResponse: {
            /** Company Id */
            company_id: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** PersonalAssessmentPayload */
        PersonalAssessmentPayload: {
            /** Criterion Id */
            criterion_id: string;
            /** Reasoning */
            reasoning?: string | null;
            /** Value */
            value: unknown;
        };
        /** PersonalAssessmentResponse */
        PersonalAssessmentResponse: {
            /** Created At */
            created_at: string;
            /** Criterion Id */
            criterion_id: string;
            /** Criterion Name */
            criterion_name: string;
            /** Id */
            id: string;
            /** Opportunity Id */
            opportunity_id: string;
            /** Origin */
            origin: string;
            /** Reasoning */
            reasoning: string | null;
            /** Revision Number */
            revision_number: number;
            /** Supersedes Id */
            supersedes_id: string | null;
            /** Value */
            value: unknown;
        };
        /** PersonalAssessmentRevisionPayload */
        PersonalAssessmentRevisionPayload: {
            /** Reasoning */
            reasoning?: string | null;
            /** Value */
            value: unknown;
        };
        /** PostingOptionResponse */
        PostingOptionResponse: {
            /** Company Id */
            company_id: string;
            /** Id */
            id: string;
            /** Opportunity Id */
            opportunity_id: string;
            /** Title */
            title: string;
        };
        /** PostingResponse */
        PostingResponse: {
            /** Availability */
            availability?: ("available" | "unavailable" | "uncertain" | "unknown") | null;
            /** Availability Age Days */
            availability_age_days?: number | null;
            /** Availability History */
            availability_history?: components["schemas"]["AvailabilityHistoryResponse"][];
            /** Availability Last Checked At */
            availability_last_checked_at?: string | null;
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Published At */
            published_at: string | null;
            source: components["schemas"]["SourceResponse"];
            source_reference: components["schemas"]["SourceReferenceResponse"];
            /** Title */
            title: string;
        };
        /** ReorderPayload */
        ReorderPayload: {
            /** Criterion Ids */
            criterion_ids: string[];
        };
        /** RestorePayload */
        RestorePayload: {
            /** Reason */
            reason?: string | null;
            /** Target Status */
            target_status?: ("new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived") | null;
        };
        /** SelectedResearchScope */
        SelectedResearchScope: {
            /** As Of Date */
            as_of_date: string;
            /** Selected Correlation Refs */
            selected_correlation_refs: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "company_update" | "opportunity_update";
        };
        /** SourceReferenceResponse */
        SourceReferenceResponse: {
            /** Display Label */
            display_label: string | null;
            /** Id */
            id: string;
            /** Observed At */
            observed_at: string;
            /** Url */
            url: string;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Base Url */
            base_url?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** StatusPayload */
        StatusPayload: {
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "to_review" | "interesting" | "shortlisted" | "deferred" | "excluded" | "archived";
        };
        /** UpdatePromptOptionsResponse */
        UpdatePromptOptionsResponse: {
            /** Companies */
            companies: components["schemas"]["CompanyOptionResponse"][];
            /** Observation Types */
            observation_types: ("technology_requirement" | "task" | "seniority" | "experience_requirement" | "work_model" | "salary")[];
            /** Opportunities */
            opportunities: components["schemas"]["OpportunityOptionResponse"][];
            /** Postings */
            postings: components["schemas"]["PostingOptionResponse"][];
        };
        /** UpdatePromptPayload */
        UpdatePromptPayload: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Gap Requests */
            gap_requests?: components["schemas"]["GapRequestPayload"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "full_update" | "company_update" | "opportunity_update" | "gap_filling";
            /** Selected Ids */
            selected_ids?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    import_file_api_availability_imports_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_api_availability_imports_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_text_api_availability_imports_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityImportTextPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_report_api_availability_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_criteria_api_criteria_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"][];
                };
            };
        };
    };
    create_criterion_api_criteria_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_criteria_api_criteria_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_criterion_api_criteria__criterion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_criterion_api_criteria__criterion_id__activation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"][];
                };
            };
        };
    };
    create_group_api_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityGroupPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_api_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_group_api_groups__group_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityGroupPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_membership_api_groups__group_id__memberships_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityGroupMembershipPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_membership_api_groups__group_id__memberships__opportunity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_group_api_groups__group_id__order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityGroupReorderPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    import_file_api_imports_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_api_imports_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_text_api_imports_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTextPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_report_api_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_map_locations_api_map_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapLocationResponse"][];
                };
            };
        };
    };
    geocode_location_api_map_locations__work_location_id__geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeResolutionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_resolution_api_map_locations__work_location_id__resolution_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapResolutionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resolution_api_map_locations__work_location_id__resolution_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_projection_api_map_projection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapProjectionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapProjectionFeatureResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: {
                group_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunity_detail_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personal_assessments_api_opportunities__opportunity_id__assessments_personal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalAssessmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_personal_assessment_api_opportunities__opportunity_id__assessments_personal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalAssessmentPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalAssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personal_assessment_history_api_opportunities__opportunity_id__assessments_personal_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalAssessmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_personal_assessment_api_opportunities__opportunity_id__assessments_personal__assessment_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalAssessmentRevisionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalAssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_history_api_opportunities__opportunity_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exclude_api_opportunities__opportunity_id__exclude_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_opportunities__opportunity_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestorePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_opportunities__opportunity_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_availability_prompt_api_prompts_availability_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityPromptPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedAvailabilityPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_initial_prompt_api_prompts_initial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitialPromptPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_update_prompt_api_prompts_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromptPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedUpdatePromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_options_api_prompts_update_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePromptOptionsResponse"];
                };
            };
        };
    };
}
